# https://docs.github.com/en/actions/guides/building-and-testing-python#testing-your-code
name: Run tests and linters (with tox)

on: [push, pull-request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          pip install tox
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
